---
title: "projekt"
output: html_document
date: "2023-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(utils)
library(stringr)
library(forcats)
library(lubridate)
library(graphics)
library(plotrix)
```


**Racunanje frekvencije žanrova**
```{r}
data <- read_csv("NetflixOriginals.csv")
data


#mozemo gledati više žanrova kao da je svaki svoj stupac ili budu svi u jednom stupcu pa da trazimo u tom stringu odredeni žanr
data_genre_sep <- separate(data,Genre,into = c("Genre_1","Genre_2","Genre_3","Genre_4"),sep = "/",remove = T)
data_genre_sep


```


**ODNOS ŽANRA I DULJINE**
**DRUGO PITANJE**
```{r}
data1 <- data_genre_sep

genre_1_runtime <-data1[,c("Genre_1","Runtime")]
genre_2_runtime <-data1[,c("Genre_2","Runtime")] 
genre_3_runtime <-data1[,c("Genre_3","Runtime")] 
genre_4_runtime <-data1[,c("Genre_4","Runtime")]

colnames(genre_1_runtime)[1] <- "Genre"
colnames(genre_2_runtime)[1] <- "Genre"
colnames(genre_3_runtime)[1] <- "Genre"
colnames(genre_4_runtime)[1] <- "Genre"

genre_runtime <- rbind(genre_1_runtime,genre_2_runtime,genre_3_runtime,genre_4_runtime)
genre_runtime
genre_runtime$Genre <- str_trim(genre_runtime$Genre)

genre_runtime$Genre[genre_runtime$Genre=="Musicial"] <- "Musical"
genre_runtime$Genre[genre_runtime$Genre=="Action thriller"] <- "Action-thriller"
genre_runtime$Genre[genre_runtime$Genre=="Heist film"] <- "Heist"
genre_runtime$Genre[genre_runtime$Genre=="Romance drama"] <- "Romantic drama"
genre_runtime$Genre[genre_runtime$Genre=="Romantic teen drama"] <- "Romantic teenage drama"
genre_runtime$Genre[genre_runtime$Genre=="Science Fiction"] <- "Science fiction"
genre_runtime$Genre[genre_runtime$Genre %in% c("Action","Action comedy","Action-adventure","Action-thriller")] <- "Action"
genre_runtime$Genre[genre_runtime$Genre %in% c("Adventure","Adventure-romance")] <- "Adventure"
genre_runtime$Genre[genre_runtime$Genre %in% c("Animated musical comedy","Animation")] <- "Animation"
genre_runtime$Genre[genre_runtime$Genre %in% c("Black comedy","Comedy","Comedy horror","Comedy mystery","Comedy-drama","Coming-of-age comedy-drama","Dark comedy","Dance comedy")] <- "Comedy"
genre_runtime$Genre[genre_runtime$Genre %in% c("Christian musical","Christmas","Christmas comedy","Christmas musical")] <- "Christmas"
genre_runtime$Genre[genre_runtime$Genre %in% c("Crime drama","Crime thriller")] <- "Crime"
genre_runtime$Genre[genre_runtime$Genre %in% c("Drama","Drama-Comedy","Supernatural drama")] <- "Drama"
genre_runtime$Genre[genre_runtime$Genre %in% c("Family","Family film")] <- "Family"
genre_runtime$Genre[genre_runtime$Genre %in% c("Historical drama","Historical-epic")] <- "Historical"
genre_runtime$Genre[genre_runtime$Genre %in% c("Horror-thriller","Horror thriller","Horror comedy","Horror anthology","Horror")] <- "Horror"
genre_runtime$Genre[genre_runtime$Genre %in% c("Musical","Musical comedy")] <- "Musical"
genre_runtime$Genre[genre_runtime$Genre %in% c("Political thriller","Psychological thriller","Psychological thriller drama")] <- "Psychological"
genre_runtime$Genre[genre_runtime$Genre %in% c("Romantic comedy","Romantic comedy-drama","Romantic drama","Romance","Romantic teenage drama","Romantic thriller")] <- "Romance"
genre_runtime$Genre[genre_runtime$Genre %in% c("Science fiction adventure","Science fiction thriller")] <- "Science fiction"
genre_runtime$Genre[genre_runtime$Genre %in% c("Sports film","Sports-drama")] <- "Sports"
genre_runtime$Genre[genre_runtime$Genre %in% c("Spy thriller","Thriller")] <- "Thriller"
genre_runtime$Genre[genre_runtime$Genre %in% c("Superhero","Superhero-Comedy")] <- "Superhero"
genre_runtime$Genre[genre_runtime$Genre %in% c("Teen comedy horror","Teen comedy-drama")] <- "Teen"
genre_runtime$Genre[genre_runtime$Genre %in% c("Variety Show","Variety show")] <- "Variety"
genre_runtime$Genre[genre_runtime$Genre %in% c("War","War drama","War-Comedy")] <- "War"


genre_runtime %>% group_by(Genre) %>% summarise(mean(Runtime))->genre_runtime_mean
genre_runtime_mean <- na.omit(genre_runtime_mean)
genre_runtime_mean


hist(genre_runtime_mean$`mean(Runtime)`,main = "Frekvenicija duljine filma",xlab = "Prosječno trajanje")
plot(as.factor(genre_runtime_mean$Genre),genre_runtime_mean$`mean(Runtime)`,type="p",xlab="žanrovi",ylab="duljina")
?plot

list_runtime <- genre_runtime_mean$`mean(Runtime)`
names(list_runtime) <- genre_runtime_mean$Genre

list_runtime %>% sort()

pie(table(genre_runtime$Genre))
genre_runtime$Genre %>% table() %>% sort()

# Create a table of the factor variable
factor_table <- table(genre_runtime$Genre)

# Convert the table to percentage
combined_percentage <- prop.table(factor_table) * 100

# Print the original table
print("Original Table:")
print(factor_table)

# Print the table as percentages
print("\nTable as Percentages:")
combined_percentage %>% sort()

barplot(table(genre_runtime$Genre))
barplot(genre_runtime_mean$`mean(Runtime)`,xlab = "trajanje")
?barplot

```
**CETVRTO PITANJE**
```{r}
data4 <- data_genre_sep

score_runtime <-data4[,c("IMDB Score","Runtime")]
score_runtime

# da smanjimo broj ocjena da je analiza lakša

score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 2.3 & score_runtime$`IMDB Score` <=2.7, 2.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 2.8 & score_runtime$`IMDB Score` <=3.2, 3)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 3.3 & score_runtime$`IMDB Score` <=3.7, 3.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 3.8 & score_runtime$`IMDB Score` <=4.2, 4)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 4.3 & score_runtime$`IMDB Score` <=4.7, 4.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 4.8 & score_runtime$`IMDB Score` <=5.2, 5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 5.3 & score_runtime$`IMDB Score` <=5.7, 5.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 5.8 & score_runtime$`IMDB Score` <=6.2, 6)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 6.3 & score_runtime$`IMDB Score` <=6.7, 6.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 6.8 & score_runtime$`IMDB Score` <=7.2, 7)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 7.3 & score_runtime$`IMDB Score` <=7.7, 7.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 7.8 & score_runtime$`IMDB Score` <=8.2, 8)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 8.3 & score_runtime$`IMDB Score` <=8.7, 8.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 8.8 & score_runtime$`IMDB Score` <=9.2, 9)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 9.3 & score_runtime$`IMDB Score` <=9.7, 9.5)
score_runtime$`IMDB Score` <- replace(score_runtime$`IMDB Score`, score_runtime$`IMDB Score` >= 9.8 & score_runtime$`IMDB Score` <=10, 10)

runtime_score <- score_runtime[order(score_runtime$Runtime),]
runtime_score


plot(runtime_score$Runtime,runtime_score$`IMDB Score`,type="p")
plot(runtime_score$`IMDB Score`,runtime_score$Runtime)

runtime_score %>% group_by(`IMDB Score`) %>% summarise(mean(Runtime))->meanRuntime_score

plot(meanRuntime_score$`IMDB Score`,meanRuntime_score$`mean(Runtime)`,xlab = "ocjena",ylab = "prosjek duljine",xlim = c(2,10),main = "Odnos ocjene i prosjeka duljine filma")


```

**TRECE PITANJE**
```{r}
data3 <- data_genre_sep
premiere_score <- data3[,c("Premiere","IMDB Score")]
str_replace(premiere_score$Premiere,"January","1, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"January","1, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"February","2, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"March","3, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"April","4, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"May","5, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"June","6, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"July","7, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"August","8, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"September","9, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"October","10, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"November","11, ")
premiere_score$Premiere <- str_replace(premiere_score$Premiere,"December","12, ")
premiere_score
premiere_score$Premiere <- mdy(premiere_score$Premiere)
premiere_score


plot(premiere_score$`IMDB Score`,month(premiere_score$Premiere),xlab = "ocjena",ylab = "mjesec premijere")

premiereMonth_score <- premiere_score
premiereMonth_score$Premiere <- month(premiereMonth_score$Premiere)
premiereMonth_score

plot(premiereMonth_score$Premiere,premiereMonth_score$`IMDB Score`,xlab = "mjesec premijere",ylab = "ocjena")

premiereMonth_score %>% group_by(Premiere) %>% summarise(mean(`IMDB Score`))->premiereMonth_score
premiereMonth_score

plot(premiereMonth_score$Premiere,premiereMonth_score$`mean(\`IMDB Score\`)`,xlim = c(1,12),xlab = "mjesec premijere",ylab = "prosjek ocjena",main = "Odnos mjeseca premijere i prosječne ocjene")



```

